### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by mpgxvii**
- Adds support for `OAuth1` auth type and `Garmin` auth (which uses `OAuth1`) and generalise auth implementation to separate `OAuth1` and `OAuth2` (#85, #90, #97, #98, #112, #114) (Solves #84) 
- Adds `createdAt` user property (#94)
- Fixes user query pagination in the frontend and backend (by default page size is `INT_MAX`) (Solves #102)
- Enables Kotlin linter (#95)
- Show reset version info in user info page (or update-rest-source-user component) (#111) (Solves #109)
- Encode uri when getting projects to allow project ids to have whitespaces (#111) (Solves #108)
- Show complete user id in update-rest-source-user component and show a tooltip with the complete user id in the user list component (#111) (Solves #107)

### CODE REVIEW

**Review by yatharthranjan — DISMISSED** [review]
LGTM. Amazing effort 👏

**Comment by yatharthranjan** [comment]
On a second note can we call this release 3.0.0? just because the changes warrant a major version bump I think.

**Comment by mpgxvii** [comment]
> On a second note can we call this release 3.0.0? just because the changes warrant a major version bump I think.

Thanks. Made the changes.

**Review by yatharthranjan — APPROVED** [review]
Thanks. LGTM

**Pull request merged**
