### PR TITLE
Upgrade angular

### PR DESCRIPTION
**Pull request by peyman-mohtashami**
* Upgraded Angular to version 12.1.4
* Changed app folder structure
* Removed bootstrap and keeps Material Design
* Added ngx-translate and translations to English and Dutch
* Localized date pickers
* Modified data table
  * Changed pagination, sort and filtering to frontend instead of backend
  * Added query params to table URL
* Added refresh token flow
* Modify table styles for tablets (Mobile is not completed yet)

### CODE REVIEW

**Comment by peyman-mohtashami** [comment]
> huge effort, nice. Could you please resolve the conflicts? Then I can review.

Done.

**Comment by blootsvoets** [comment]
It looks good to me except one thing: when I log in for the first time to ManagementPortal and get sent back, I need to provide a http basic authentication. If I cancel this, there's an error alert in the login box with `[Object object]`

**Comment by blootsvoets** [comment]
Other small issues:
- clicking a subject dialog will show openSubjectDialog – "add" in the console.
- I once got an error in console about undefined locale nl-NL, but I cannot reproduce it.

**Comment by blootsvoets** [comment]
I cannot reproduce the login issue now unfortunately...

**Review by blootsvoets — APPROVED** [review]
Thanks for the updates. LGTM!

**Pull request merged**
